name: programmers
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn
      - name: Test TypeScript solutions
        run: yarn jest
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with pytest
        run: |
          pip install pytest
          pytest programmers.com/learn/courses/30/lessons/*.py
